### ISSUE TITLE
Cleanup tracker

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-wasm#8]
- [x] replace all `t[1:3]` with `get_bit_size(t)` #6 
- replace `Exception` usage with specific exception classes
  - [x] same with `"trap"` - #12 
  - [x] same with `"exhaustion"` #13 
  - [x] same with `"invalid"` #14 
  - [x] same with `"malformed"`
- [x] replace `2 ** 32 - 1` with constant #9 
  - same with `2 ** 32`
- [ ] replace use of magic string `"Unknown"` in ``spec_pop_opd` with constant.

**Comment by pipermerriam** [comment]
Make formal types for things in https://webassembly.github.io/spec/core/bikeshed/index.html#types%E2%91%A8 probably as `NamedTuple`

**Comment by pipermerriam** [comment]
Next steps:

- [ ] formalization of typing for the validation code
- [ ] run coverage and nuke dead functions
- [ ] grok `wasm.main` for `TODO` comments and do relevant cleanup or create issues
- [ ] docstring and cross-reference-spec links

Then to finish getting rid of `wasm.main` module.

- [ ] full audit for consistent and semantically meaningful variable names
- [ ] convert legacy parsers to stream parsers
- [ ] refactor validation code into smaller units of functionality
- [ ] refactor and organize opcode logic functions
- [ ] refactor how allocations and initialization works

Then to round the library out

- [ ] get floating point tests passing
- [ ] implement IR -> binary serialization
- [ ] implement "text" module parsing
- [ ] implement IR -> text serialization
